version: "3.8"

services:
  app:
    build: .
    container_name: todolist-api
    ports:
      - "8080:8080"
    depends_on:
      - pg
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://pg:5432/goal_track_db
      SPRING_DATASOURCE_USERNAME: docker
      SPRING_DATASOURCE_PASSWORD: docker
    networks:
      - backend

  pg:
    image: bitnami/postgresql:17.4.0
    container_name: postgres-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pgdata:/bitnami/postgresql
    networks:
      - backend

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - pg
    networks:
      - backend

volumes:
  pgdata:

networks:
  backend:
